#!/bin/bash
usage () {
  	echo "Usage:"
  	echo -e "  mem \e[3m<your search>\e[0m"	
	echo "  mem -h  (display help)"
}
while getopts "h" opt
do
	case $opt in
		h)  usage
		    exit 0;;
		?)  usage
		    exit 1;;
	esac
done


if [ -z "$1" ]
then
  	echo "Error: No search provided"
  	usage
  	exit 1
else
  	output=$(ps -eo comm,rss --sort=comm | grep $1 | awk '{$2=$2/1024;}{printf("%-20s %.2fMB\n", $1, $2)}')
  	if [ -z "$output" ]
    	then
		echo "No processes matching $1"
		exit 1
	else
	echo "${output}"
	fi
fi
exit 0

